name: 🧪 Python CI

on:
  pull_request:
    branches: [main, v1.0]

jobs:
  branch-naming:
    name: Check branch naming
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch name
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ "$BRANCH" =~ ^(ag|yk)[0-9]{6}(_[0-9]+)?$ || "$BRANCH" =~ ^(fix|feature|v)+ ]]; then
            echo "Branch name '$BRANCH' is valid."
          else
            echo "Invalid branch name '$BRANCH'. Allowed: agDDMMYY(_n), ykDDMMYY(_n), fix/..., feature/..., v..."
            exit 1
          fi

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: branch-naming

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest tests/

  lint:
    name: Ruff linter
    runs-on: ubuntu-latest
    needs: branch-naming

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check . --output-format=github

